name: travel_map_f
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  fluttery: 0.0.5
  sqflite: any
  path_provider: ^0.3.1
  rxdart: ^0.16.1
  flutter_webview_plugin: ^0.1.4
  map_view: 0.0.12

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/places.json
    - assets/bosnia_cover.jpg
    - assets/croatia_cover.jpg
    - assets/france_cover.jpg
    - assets/germany_cover.jpg
    - assets/hungary_cover.jpg
    - assets/montenegro_cover.jpg
    - assets/romania_cover.jpg
    - assets/serbia_cover.jpg
    - assets/spain_cover.jpg
    - assets/croatia.png
    - assets/germany.png
    - assets/hungary.png
    - assets/montenegro.jpg
    - assets/romania.png
    - assets/serbia.png
    - assets/spain.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: petita
       fonts:
         - asset: assets/fonts/PetitaMedium.ttf
         - asset: assets/fonts/PetitaBold.ttf
           weight: 700
         - asset: assets/fonts/PetitaLight.ttf
           weight: 300
     - family: gidole
       fonts:
         - asset: assets/fonts/Gidole-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
